version: "3.8"
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: mc
    environment:
      EULA: "TRUE"
    ports:
      - "25565:25565"
    volumes:
      - "./server-data:/data"
    restart: unless-stopped
