version: "3.8"
services:
  ngrok:
    image: ngrok/ngrok
    command: "tcp 25565"
    environment:
      NGROK_AUTHTOKEN: "xxxx"
    restart: always
  minecraft-server:
    image: itzg/minecraft-server
    container_name: mc
    environment:
      EULA: "TRUE"
    ports:
      - "25565:25565"
    volumes:
      - "./server-data:/data"
    restart: unless-stopped
    depends_on:
      - "ngrok"